# Generated by Django 5.2.4 on 2026-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('owner_color', models.CharField(blank=True, max_length=7, null=True)),
                ('claimed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('x', 'y')},
            },
        ),
    ]
